version: 2

builds:
  - main: cmd/gh-codeowners/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X go.szostok.io/version.version={{.Version}}
      - -X go.szostok.io/version.buildDate={{.Date}}

archives:
  - name_template: "gh-codeowners-{{ .Os }}-{{ .Arch }}"
    format: binary

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
